// Build step: read the bundled excerpt YAML under corpus/ and emit a typed
// TS module (src/corpus/corpus.data.ts) of raw records. Keeping the corpus as
// generated TS means the runtime needs no YAML parser and `bun build --compile`
// embeds it into the single binary. Re-run after editing corpus/*.yml:
//
//   bun run build:corpus
//
// Taxonomy (language / category / speed_band) is derived from the file path,
// exactly as frank_type's ExcerptCatalog#load_records does.

import { Glob } from "bun";
import { parse } from "yaml";
import { readFileSync } from "node:fs";
import { join, relative } from "node:path";
import type { RawExcerpt } from "../src/corpus/excerpt_catalog";

const CORPUS_DIR = join(import.meta.dir, "..", "corpus");
const OUT_FILE = join(import.meta.dir, "..", "src", "corpus", "corpus.data.ts");

interface YamlRecord {
  id: string;
  title: string;
  author: string;
  source: string;
  source_url: string;
  text: string;
  language?: string;
  category?: string;
  speed_band?: string;
}

const records: RawExcerpt[] = [];

for (const path of new Glob("**/*.yml").scanSync(CORPUS_DIR)) {
  // path is e.g. "en/scifi/slow.yml" → [language, category, band].
  const [language, category, band] = path.split(/[\\/]/);
  const speedBand = (band ?? "").replace(/\.yml$/, "");
  const entries = parse(readFileSync(join(CORPUS_DIR, path), "utf8")) as YamlRecord[];

  for (const entry of entries) {
    records.push({
      id: entry.id,
      title: entry.title,
      author: entry.author,
      source: entry.source,
      source_url: entry.source_url,
      text: foldText(entry.text),
      language: entry.language ?? language ?? "",
      category: entry.category ?? category ?? "",
      speed_band: entry.speed_band ?? speedBand,
    });
  }
}

// Deterministic order: language, category, speed_band, id.
records.sort(
  (a, b) =>
    a.language.localeCompare(b.language) ||
    a.category.localeCompare(b.category) ||
    a.speed_band.localeCompare(b.speed_band) ||
    a.id.localeCompare(b.id),
);

/** YAML folded scalars keep a trailing newline; trim it as Ruby's loader does. */
function foldText(text: string): string {
  return text.trimEnd();
}

const banner = `// GENERATED by scripts/build-corpus.ts from corpus/**/*.yml — do not edit.
// Re-run \`bun run build:corpus\` after changing the YAML corpus.
import type { RawExcerpt } from "./excerpt_catalog";
`;

const body = `\nexport const RAW_EXCERPTS: readonly RawExcerpt[] = ${JSON.stringify(records, null, 2)};\n`;

await Bun.write(OUT_FILE, banner + body);
console.log(`Wrote ${records.length} excerpts to ${relative(process.cwd(), OUT_FILE)}`);
